version: "3.5"

volumes:
    dbdata:

services:
    database:
        container_name: postgres
        environment:
            PGDATA: /var/lib/postgresql/data/pgdata
            POSTGRES_DB: crude_db
            POSTGRES_PASSWORD: password
        image: postgres:11.0-alpine
        ports:
            - 5432:5432
        expose:
            - 5432
        volumes:
            - dbdata:/var/lib/postgresql/data/pgdata
            - ./db/db.sql:/docker-entrypoint-initdb.d/db.sql
    backend:
        container_name: backend
        environment:
            DB_HOST: postgres
            DB_NAME: crude_db
            DB_USER: postgres
            DB_PASSWORD: password
            DB_PORT: 5432
            DB_SCHM: public
        image: python:3.7.6-slim
        working_dir: /opt/app
        command: ["sh", "startup.sh"]
        ports:
            - 8080:8080
        expose:
            - 8080
        volumes:
            - ./:/opt/app
        depends_on:
            - database
