version: "3.5"

volumes:
    dbdata:

services:
    postgres:
        container_name: postgres
        environment: :
            PGDATA: "/var/lib/postgresql/data/pgdata"
            POSTGRES_DB: postgres
            POSTGRES_PASSWORD: password
            POSTGRES_USER: postgres
        image: postgres:10.11-alpine
        ports:
            - "5432:5432"
        volumes:
            - "dbdata:/var/lib/postgresql/data/pgdata"
